[
    {
        "FirstName":"Name1",
        "LastName":"LastName1",
        "Email":"name1@gmail.com",
        "Age":23,
        "Operation":"login",
        "EmptyValue":null,
        "result1":"res1",
        "result2":213.25,
        "result3":true
    }
]